[package]
name = "circuits_constraints_and_algebra"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint-dig = "0.6.0"
num-traits = "0.2.6"
utils = {path = "../utils" }
constant_tracking = {path = "../constant_tracking" }
z3 = {version="0.20.0"}
circuits_constraints_and_algebra = {path = "../circuits_constraints_and_algebra" }
either = "1.15.0"
itertools = "0.14.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
rustsat = "0.7.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
